### ISSUE TITLE
Windows Error: Could not open library 'libcurl.so.4.dll'

### ISSUE THREAD

**Issue by dotnetdan** [benbalter/jekyll-remote-theme#18] opened 2017-12-12 15:51 UTC
On Windows 7, I'm unable to to run Github Pages locally. Is this expected? Does jekyll-remote-theme still have a dependency on libcurl?

Config.yml

    remote_theme: benbalter/retlab

    plugins:
       - jekyll-feed
       - jekyll-remote-theme

Gem file

    gem 'jekyll-remote-theme', github: 'benbalter/jekyll-remote-theme', branch: 'master'

    group :jekyll_plugins do
      gem "jekyll-feed", "~> 0.6"
    end

I run `$ bundle exec jekyll serve`

Configuration file: C:/Users/Daniel.Ling/source/repos/dotnetdan-github-io/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-remote-theme or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'Could not open library 'libcurl': The specified module could not be found. . Could not open library 'libcurl.dll': The specified module could not be found. . Could not open library 'libcurl.so.4': The specified module could not be found. . Could not open library 'libcurl.so.4.dll': The specified module could not be found. ' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!

**Comment by DirtyF** [comment] 2017-12-12 16:40
Could you try the following procedure: https://github.com/benbalter/jekyll-remote-theme/issues/17#issuecomment-350818119 ?

**Comment by dotnetdan** [comment] 2017-12-12 20:17
@DirtyF I am trying to follow the instructions, but I can't seem to find the proper libcurl download - the only windows libcurl downloads are for cygwin, and I don't think that is correct?

**Comment by koppor** [comment] 2018-01-21 14:52
A pointer in the direction of the solution could be https://stackoverflow.com/a/47754520/873282. For me, Jekyll now starts, but I get following error:

> Remote Theme: Using theme mmistakes/minimal-mistakes                                     
> jekyll 3.6.2 | Error:  Peer certificate cannot be authenticated with given CA certificates

**Comment by jengalas** [comment] 2018-01-21 22:09
@koppor I'm getting the same error. Did you have any luck resolving this yet?

**Comment by koppor** [comment] 2018-01-21 22:24
@jengalas No, I just downloaded the theme to my local git repository to keep things moving. I could have used the [jeckyll docker image](https://github.com/envygeeks/jekyll-docker/blob/master/README.md) as another workaround, but that seemed to be too complex for my case.

**Comment by jengalas** [comment] 2018-01-22 00:30
Thank you! I'll investigate the docker image if necessary.

**Comment by zvirja** [comment] 2018-01-22 14:27
@benbalter Do you have any chance to review the issue? It's kind a mess around all that stuff with GitHub pages and it's impossible to find any fully suitable workaround😕

**Comment by DirtyF** [comment] 2018-01-22 15:55
As this issue is related to GitHub Pages install on Windows, feel free to [contact GitHub support](https://github.com/contact).

**Comment by zvirja** [comment] 2018-01-22 15:59
@DirtyF The situation isn't that simple as described [here](https://github.com/jekyll/jekyll/issues/6660#issuecomment-354690545). As far as I got, the issue is not even related this component - it's caused by [`Typhoeus`](https://github.com/typhoeus/typhoeus/issues/585). However, you are probably right - it's better to contact them. Will write a letter to see whether they could facilitate the process 😉

**Comment by nesdis** [comment] 2018-01-23 14:17
@koppor Once you clone the theme locally, how do you point to it so you can proceed further??

**Comment by mmistakes** [comment] 2018-01-23 14:24
Hit the same issue on #9. As far as I could tell libcurl was installed properly and I had a valid certificate. Eventually gave up trying to get remote theme working on Windows thinking it was something related to my specific environment. Maybe not...

**Comment by koppor** [comment] 2018-01-23 14:48
@nesdis This is the "magic" of Jekyll. Here my repo: https://github.com/koppor/wiki.flupp.de/ - I followed the how to of the "minimal mistakes theme" here: https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

**Comment by jengalas** [comment] 2018-01-23 15:04
I only have Windows machines to use for development, and I couldn't resolve the certificate error. I ended up hosting on Netlify instead of Github Pages; no problems.

**Comment by benbalter** [comment] 2018-01-23 16:19
[Version 174](https://github.com/github/pages-gem/releases/tag/v174) of the Pages Gem makes the Jekyll Remote Theme dependency optional, and should resolve issues for Windows users trying to preview sites locally that don't use a remote theme. Those wanting to preview a theme locally will need to following the troubleshooting steps above to install cURL in their local environment.

**Comment by nesdis** [comment] 2018-01-23 16:30
@benbalter What exactly are the steps to install cURL Could you please provide a url

**Comment by benbalter** [comment] 2018-01-23 16:37
> What exactly are the steps to install cURL Could you please provide a url

https://github.com/benbalter/jekyll-remote-theme/issues/17#issuecomment-350818119

**Closed** 2018-03-31 18:15 UTC
Labels: wontfix

**Comment by benbalter** [comment] 2018-05-14 14:13
Version 0.3.0 uses Ruby's native Net:HTTP, instead of Typhoeus (Libcurl), which may alleviate this issue.

**Comment by benbalter** [comment] 2018-05-14 19:34
I haven't seen that before, but _think_ that's safe to ignore as it's an artifact of Jekyll looking for the `_sass` folder before the theme's been downloaded, but we configure it manually once it is.
